apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-local
  namespace: argocd
spec:
  ingressClassName: nginx
  rules:
  - host: argocd.toannc.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argo-server
            port:
              number: 443

